name: Publish release
on:
  release:
    types: [created]
jobs:
  release-js:
    name: jsbt v0.6.2
    uses: paulmillr/jsbt/.github/workflows/release.yml@e7792651088ad10a04fd63f76760a3465cc5c076
    permissions:
      contents: read
      id-token: write
