name: Run tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-ts:
    name: jsbt v0.6.2
    uses: paulmillr/jsbt/.github/workflows/test.yml@e7792651088ad10a04fd63f76760a3465cc5c076
